/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersCreateRouteImport } from './routes/users/create'
import { Route as PokemonsGetPokemonStatsRouteImport } from './routes/pokemons/getPokemonStats'
import { Route as PokemonsCreateOpinionRouteImport } from './routes/pokemons/createOpinion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersCreateRoute = UsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsGetPokemonStatsRoute = PokemonsGetPokemonStatsRouteImport.update({
  id: '/pokemons/getPokemonStats',
  path: '/pokemons/getPokemonStats',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsCreateOpinionRoute = PokemonsCreateOpinionRouteImport.update({
  id: '/pokemons/createOpinion',
  path: '/pokemons/createOpinion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons/createOpinion': typeof PokemonsCreateOpinionRoute
  '/pokemons/getPokemonStats': typeof PokemonsGetPokemonStatsRoute
  '/users/create': typeof UsersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemons/createOpinion': typeof PokemonsCreateOpinionRoute
  '/pokemons/getPokemonStats': typeof PokemonsGetPokemonStatsRoute
  '/users/create': typeof UsersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokemons/createOpinion': typeof PokemonsCreateOpinionRoute
  '/pokemons/getPokemonStats': typeof PokemonsGetPokemonStatsRoute
  '/users/create': typeof UsersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pokemons/createOpinion'
    | '/pokemons/getPokemonStats'
    | '/users/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pokemons/createOpinion'
    | '/pokemons/getPokemonStats'
    | '/users/create'
  id:
    | '__root__'
    | '/'
    | '/pokemons/createOpinion'
    | '/pokemons/getPokemonStats'
    | '/users/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonsCreateOpinionRoute: typeof PokemonsCreateOpinionRoute
  PokemonsGetPokemonStatsRoute: typeof PokemonsGetPokemonStatsRoute
  UsersCreateRoute: typeof UsersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/create': {
      id: '/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof UsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/getPokemonStats': {
      id: '/pokemons/getPokemonStats'
      path: '/pokemons/getPokemonStats'
      fullPath: '/pokemons/getPokemonStats'
      preLoaderRoute: typeof PokemonsGetPokemonStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/createOpinion': {
      id: '/pokemons/createOpinion'
      path: '/pokemons/createOpinion'
      fullPath: '/pokemons/createOpinion'
      preLoaderRoute: typeof PokemonsCreateOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonsCreateOpinionRoute: PokemonsCreateOpinionRoute,
  PokemonsGetPokemonStatsRoute: PokemonsGetPokemonStatsRoute,
  UsersCreateRoute: UsersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
